logging:
  level:
    org:
      springframework:
        security: DEBUG   # Logs security decisions
        web:
          FilterChainProxy: DEBUG   # Logs which filters apply to which request

spring:
#  security:
#    oauth2:
#      client:
#        registration: 
#          google:
#            clientId: 847747434266-ghg1mghtfe6q54bu41iabsaesi0ordkv.apps.googleusercontent.com
#            clientSecret: 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
# ...
  application:
    name: customerservice
  main:
    allow-circular-references: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/customerService

server:
  port: 8083
  servlet:
    context-path: /api

# fast2sms:
#   api:
#     key: OweFpXlzqggSfLbCjNsokpsvpWG5uffME0TkMmTjRlDJVnu40JXGfpuUrOFg

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      circuitBreaker:
        failure-rate-threshold: 80
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 4
        wait-duration-in-open-state: 1m

app:
  firebase-configuration-file: firebase-key.json